---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route_question(route_question)
	llm_fallback(llm_fallback)
	generate(generate)
	transform_query(transform_query)
	__end__([<p>__end__</p>]):::last
	__start__ --> route_question;
	llm_fallback --> __end__;
	transform_query --> search_data_analyze_question;
	route_question -.-> llm_fallback;
	route_question -.-> search_data_analyze_question;
	search_data_filter_documents -.-> transform_query;
	search_data_filter_documents -.-> generate;
	generate -. &nbsp;not useful&nbsp; .-> transform_query;
	generate -. &nbsp;useful&nbsp; .-> __end__;
	generate -. &nbsp;end&nbsp; .-> __end__;
	subgraph search_data
	search_data_analyze_question(analyze_question)
	search_data_search_fixed_deposit(search_fixed_deposit)
	search_data_search_demand_deposit(search_demand_deposit)
	search_data_filter_documents(filter_documents)
	search_data_search_demand_deposit --> search_data_filter_documents;
	search_data_search_fixed_deposit --> search_data_filter_documents;
	search_data_analyze_question -.-> search_data_search_fixed_deposit;
	search_data_analyze_question -.-> search_data_search_demand_deposit;
	end
	generate -. &nbsp;not supported&nbsp; .-> generate;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
